import { Disclosure } from "./Disclosure";
import { AmbientVideo, HeroLines, BotanicalMark } from "./Motion";
import {useState} from "react";
import {asset,DemoBar,Modal,SiteFooter,SiteHeader} from "./Shared";
import "./mellow.css";
import "../sample-fonts.css";
import "./responsive.css";
const money=(n:number)=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY"}).format(n);
export default function Mellow(){const [size,setSize]=useState<"250 mL"|"500 mL">("250 mL");const [qty,setQty]=useState(1);const [cart,setCart]=useState<Record<string,number>>({});const [open,setOpen]=useState(false);const [confirmed,setConfirmed]=useState(false);const [photo,setPhoto]=useState("全体");const price=size==="250 mL"?3200:5200;const total=Object.entries(cart).reduce((s,[k,q])=>s+q*(k==="250 mL"?3200:5200),0);const count=Object.values(cart).reduce((s,n)=>s+n,0);
function add(){setCart(c=>({...c,[size]:(c[size]||0)+qty}));setConfirmed(false);setOpen(true);}
return <div className="sample-full mellow-page" id="top"><a className="ss-skip" href="#main">本文へ移動</a><DemoBar site="mellow"/><SiteHeader logo="mellow" links={[["OUR STORY","#story"],["PRODUCT","#product"],["YOUR RITUAL","#ritual"]]} action={<button className="mellow-bag" onClick={()=>{setConfirmed(false);setOpen(true);}} aria-label={`バッグを見る ${count}点`}>BAG <span>{count}</span></button>}/>
<main id="main"><section className="mellow-hero" data-hero data-scene><img className="ss-photo-drift ss-loop" src={asset("mellow-botanical.webp")} alt="自然光に包まれたmellowのボタニカルボディミルク" fetchPriority="high" width={1122} height={1402}/><AmbientVideo/><div className="mellow-hero-copy"><p className="ss-eyebrow">A MOMENT, JUST FOR YOU.</p><h1><HeroLines first="A little" second={<em>closer to nature.</em>}/></h1><p>肌にも、心にも。<br/>自然体の心地よさを。</p><a className="ss-button" href="#product">Discover mellow</a></div><div className="mellow-hero-caption"><span>BOTANICAL BODY MILK</span><span>THE DAILY RITUAL / 01</span></div></section>
<section className="ss-section mellow-story" id="story" data-reveal data-scene><BotanicalMark/><p data-scroll-anchor className="ss-eyebrow">OUR STORY</p><h2>がんばる毎日に、<br/>ひと呼吸の余白を。</h2><p>朝の光。ほのかな香り。<br/>肌に触れる、なめらかな感触。</p><p>毎日のケアが、ただの習慣から<br/>自分をいたわる、小さな時間に変わるように。<br/>mellowは、心地よさから生まれた<br/>ボタニカルケアのコンセプトブランドです。</p><span className="mellow-story-word" aria-hidden="true">less hurry, more mellow.</span></section>
<section className="mellow-notes"><div className="mellow-detail-image" data-parallax="42" data-scene><img src={asset("mellow-botanical.webp")} alt="すりガラスと植物の影がつくる、柔らかな陰影" loading="lazy"/><AmbientVideo/><span>SOFTLY. SIMPLY. EVERY DAY.</span></div><div className="mellow-notes-copy" data-reveal><p className="ss-eyebrow">THE FEELING OF MELLOW</p><h2>心地よさを、<br/>ひとつずつ。</h2>{[["01","Soft touch","手に取る瞬間から、やわらかく。肌になじませる時間そのものを楽しむための、ボディミルクというかたち。"],["02","Quiet scent","深呼吸したくなる、穏やかなグリーンのイメージ。暮らしの邪魔をせず、そっと寄り添う香りを思い描いて。"],["03","Simple ritual","お気に入りの一つを、毎日のそばに。飾りたくなるボトルと、続けたくなるシンプルな習慣。"]].map(([n,t,p])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></article>)}</div></section>
<section className="ss-section mellow-product" id="product"><div className="mellow-product-gallery"><div className={`mellow-product-photo ${photo==="質感"?"is-detail":""}`}><img src={asset("mellow-botanical.webp")} alt={photo==="全体"?"mellowボディミルクのボトル全体":"ボトル表面の質感を拡大したイメージ"} loading="lazy"/></div><div className="ss-filter" aria-label="商品画像の切り替え">{["全体","質感"].map(v=><button key={v} aria-pressed={photo===v} onClick={()=>setPhoto(v)}>{v}</button>)}</div></div><div className="mellow-product-info" data-reveal><p data-scroll-anchor className="ss-eyebrow">THE DAILY RITUAL / 01</p><h2>Botanical<br/><em>body milk.</em></h2><p className="mellow-product-ja">ボタニカル ボディミルク</p><p>慌ただしい日にも、自分に戻るひとときを。<br/>自然な心地よさを思い描いた、<br/>毎日のためのボディケア。</p><p className="mellow-price">{money(price)} <small>税込・サンプル価格</small></p><fieldset className="mellow-size"><legend>容量</legend>{(["250 mL","500 mL"] as const).map(s=><label key={s}><input type="radio" name="size" value={s} checked={size===s} onChange={()=>setSize(s)}/><span>{s}</span></label>)}</fieldset><label className="mellow-quantity">数量<select value={qty} onChange={e=>setQty(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button className="ss-button mellow-add" onClick={add}>バッグに追加（デモ）</button><p className="ss-demo-note">架空の商品です。カート操作を体験できますが、注文・決済・配送は行われません。</p><Disclosure title="商品コンセプト"><p>すりガラスのボトル、落ち着いたグリーン、日常に溶け込む佇まい。植物から着想したブランドの世界観を表現しています。実際の配合成分や効能を示すものではありません。</p></Disclosure><Disclosure title="パッケージについて"><p>250 mLと500 mLのサイズ選択を体験できます。掲載画像はデザインイメージのため、サイズ選択で容器の画像は変わりません。</p></Disclosure></div></section>
<section className="ss-section mellow-ritual" id="ritual" data-reveal><p data-scroll-anchor className="ss-eyebrow">MAKE TIME FOR YOURSELF</p><h2>Your everyday,<br/><em>a little softer.</em></h2><div>{[["01","Pause.","手を止めて、ひと呼吸。","お風呂上がりや、一日の終わりに。今日の自分に目を向ける、小さな合図。"],["02","Feel.","手のひらから、ゆっくり。","感触や香りを感じながら。急がず、肌に触れる時間を楽しんで。"],["03","Be mellow.","心地よいまま、明日へ。","特別なことをしなくても。自分をいたわる時間を、毎日の習慣に。"]].map(([n,t,j,p])=><article key={n}><span>{n} / YOUR RITUAL</span><h3>{t}</h3><h4>{j}</h4><p>{p}</p></article>)}</div></section>
<section className="ss-section mellow-faq" id="faq"><div><p data-scroll-anchor className="ss-eyebrow">A FEW LITTLE ANSWERS</p><h2>Good to know.</h2></div><div>{[["この商品を購入できますか？","このサイトはISAACが制作した架空ブランドのデザインサンプルです。商品の販売は行っていません。容量選択・カート追加・内容確認までの操作をお試しいただけます。"],["カートに入れた内容は保存されますか？","このページを開いている間だけ保持されます。ページの再読み込みや移動でリセットされ、外部へ送信されません。"],["こうした商品サイトの制作を相談できますか？","はい。画面上部または下部の「ISAACに戻る」から、Web制作の無料相談へお進みいただけます。"]].map(([q,a])=><Disclosure key={q} title={q}><p>{a}</p></Disclosure>)}</div></section>
<section className="mellow-closing" data-scene><AmbientVideo/><p className="ss-eyebrow">A SMALL MOMENT. A BETTER EVERYDAY.</p><h2>Make room<br/>for <em>mellow.</em></h2><a className="ss-button" href="#product">商品をもう一度見る</a></section></main><SiteFooter brand="mellow" tagline="肌にも、心にも。自然体の心地よさを。"/>
{open&&<Modal title={confirmed?"Thank you for trying.":`Your bag (${count})`} close={()=>setOpen(false)}>{confirmed?<div className="ss-form-result"><h3>カートの内容を確認しました。</h3><p>デモ体験はここまでです。注文や決済は発生していません。</p><button className="ss-button" onClick={()=>setOpen(false)}>サイトに戻る</button></div>:count===0?<div className="ss-form-result"><p>バッグはまだ空です。</p><a className="ss-button" href="#product" onClick={()=>setOpen(false)}>商品を見る</a></div>:<><p className="ss-demo-note">デモカートです。購入や支払いは発生しません。</p>{Object.entries(cart).filter(([,q])=>q>0).map(([s,q])=><div className="mellow-cart-item" key={s}><img src={asset("mellow-botanical.webp")} alt="ボディミルク"/><div><h3>Botanical body milk</h3><p>{s} / {money(s==="250 mL"?3200:5200)}</p><label>数量<select aria-label={`${s}の数量`} value={q} onChange={e=>setCart(c=>({...c,[s]:Number(e.target.value)}))}>{Array.from({length:Math.max(10,q)},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label><button className="ss-text-link" onClick={()=>setCart(c=>{const n={...c};delete n[s];return n;})}>削除</button></div></div>)}<p className="mellow-cart-total">合計（税込） <strong>{money(total)}</strong></p><button className="ss-button" onClick={()=>setConfirmed(true)}>内容を確認する（デモ）</button></> }</Modal>}
</div>;}
