import { HeroLines, MotionMarquee } from "./Motion";
import {useState} from "react";
import team from "../assets/generated/hero/hero-team.webp";
import personDesign from "../assets/generated/people/person-growth.webp";
import personEngineer from "../assets/generated/people/person-se.webp";
import workshop from "../assets/generated/growth/growth-workshop.webp";
import {NavigationIcon,DemoBar,DemoForm,Modal,SiteFooter,SiteHeader} from "./Shared";
import "./next.css";
import "../sample-fonts.css";
const jobs=[{title:"プロダクトデザイナー",category:"DESIGN",body:"ユーザーの声から課題を見つけ、体験の設計からUIの表現までを担います。エンジニアと一緒に、つくって試すことを大切にする仕事です。",skills:"Web・アプリのUI設計経験、意図を伝えながらチームで制作を進めた経験。"},{title:"フロントエンドエンジニア",category:"ENGINEERING",body:"プロダクトの使いやすさを、実装からつくります。デザイナーと協働しながら、パフォーマンスやアクセシビリティも含めて体験を磨きます。",skills:"HTML・CSS・JavaScriptでの開発経験、チーム開発への関心。"},{title:"プロジェクトプランナー",category:"BUSINESS",body:"事業の課題を整理し、チームの力が届く道筋をつくります。企画・進行・振り返りを通じて、プロジェクトの一歩先を考える仕事です。",skills:"プロジェクトの進行経験、さまざまな立場の人と対話する力。"}];
const people=[{name:"Haru",role:"PRODUCT DESIGNER",image:personDesign,title:"「こうしたい」を、\n一緒に面白がってくれる。",body:"ひとりで考えていたアイデアを話すと、誰かが別の視点を足してくれる。ここでは、未完成のまま相談できることが強さになっています。毎週のデザインレビューでも、立場より「なぜそう考えたか」を大切にしています。"},{name:"Ren",role:"FRONTEND ENGINEER",image:personEngineer,title:"いい体験は、\n職種の境目を越えてくる。",body:"デザインができる前から、一緒に画面を考えます。小さく実装して触ってみると、会議だけでは見つからない答えがある。技術を学ぶ時間と、隣の人に質問できる空気が、自分の成長を支えてくれています。"}];
export default function Next(){const [filter,setFilter]=useState("ALL");const [person,setPerson]=useState<number|null>(null);const [job,setJob]=useState<number|null>(null);const [entry,setEntry]=useState("まずはカジュアルに話したい");
return <div className="sample-full next-page" id="top"><a className="ss-skip" href="#main">本文へ移動</a><DemoBar site="next"/><SiteHeader logo={<>next<span>.</span><small>RECRUITING SITE</small></>} links={[["私たちのこと","#about"],["働く人","#people"],["カルチャー","#culture"]]} action={<a className="ss-button" href="#jobs">募集職種を見る</a>}/>
<main id="main"><section className="next-hero" data-hero data-scene><div className="next-hero-copy"><p className="ss-eyebrow">YOUR NEXT CHAPTER STARTS HERE.</p><h1><HeroLines first="次の自分を、" second={<em>おもしろく。</em>}/></h1><p>まだない答えを、一緒につくろう。</p><a className="ss-text-link" href="#people">働く仲間を知る</a><span className="next-big-star ss-loop" aria-hidden="true">✳</span></div><div className="next-hero-photo"><img className="ss-photo-drift ss-loop" src={team} alt="テーブルを囲んでアイデアを話し合うチーム" width={1586} height={992} fetchPriority="high"/></div><p className="next-hero-bottom"><span>MAKE IT TOGETHER.</span>その一歩が、チームの未来になる。</p></section>
<MotionMarquee/><section className="ss-section next-about" id="about" data-reveal><p className="ss-eyebrow">01 / WHO WE ARE</p><div><h2>正解を待つより、<br/><span>一緒につくろう。</span></h2><p>私たちは、デザインとテクノロジーで<br/>人と事業の「次」をつくるチームです。</p><p>まずやってみる。違う視点を歓迎する。<br/>うまくいかない日も、面白がって前へ進む。<br/>そんな仲間となら、まだ見ぬ景色にたどり着ける。</p></div><span className="next-about-mark" data-scroll-turn aria-hidden="true">n.</span></section>
<section className="ss-section next-people" id="people"><div className="ss-section-head" data-reveal><div><p className="ss-eyebrow">02 / PEOPLE</p><h2>一人ひとりが、<br/>このチームの色。</h2></div><p>得意なことも、歩んできた道も違う。<br/>だから、一緒につくると面白い。</p></div><div className="next-people-grid">{people.map((p,i)=><button className="next-person" key={p.name} onClick={()=>setPerson(i)}><div><img width={1122} height={1402} src={p.image} alt={`${p.name}の人物イメージ`} loading="lazy"/></div><p className="ss-eyebrow">{p.role} / {p.name}</p><h3>{p.title}</h3><span className="next-person-action">インタビューを読む<NavigationIcon/></span></button>)}</div><p className="ss-caption">人物・インタビューは、採用サイトの表現を体験するための架空のストーリーです。</p></section>
<section className="next-culture" id="culture"><div className="next-culture-visual" data-parallax="50"><img src={workshop} alt="アイデアを持ち寄るワークショップのイメージ" loading="lazy"/><p data-enter>GOOD WORK.<br/>BETTER TOGETHER.</p></div><div className="ss-section"><p className="ss-eyebrow">03 / CULTURE</p><h2>いい仕事は、<br/>いいチームから。</h2><div className="next-values">{[["01","まず、やってみよう。","小さく試して、早く学ぶ。完成まで抱え込まず、途中のアイデアを持ち寄ります。"],["02","違いを、面白がろう。","専門や経験の違いは、チームの可能性。相手の背景まで聞くことを大切にします。"],["03","学びを、ひらこう。","見つけたことは、仲間へ。レビューや勉強会で、個人の学びをチームの力にします。"]].map(([n,t,p])=><article key={n} data-reveal><span>{n} / OUR VALUE</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
<section className="ss-section next-jobs" id="jobs"><div className="ss-section-head" data-reveal><div><p className="ss-eyebrow">04 / OPEN POSITIONS</p><h2>あなたの「次」は、<br/>どこから始まる？</h2></div><p>経験を生かすことも、新しい挑戦も。<br/>まずは、気になる仕事から。</p></div><div className="ss-filter" aria-label="職種の絞り込み">{["ALL","DESIGN","ENGINEERING","BUSINESS"].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><p className="ss-caption" aria-live="polite">{jobs.filter(j=>filter==="ALL"||j.category===filter).length}件のサンプル募集職種</p><div>{jobs.map((j,i)=>(filter==="ALL"||j.category===filter)&&<button className="next-job" onClick={()=>setJob(i)} key={j.title}><span>{j.category}</span><h3>{j.title}</h3><NavigationIcon/></button>)}</div></section>
<section className="ss-section next-entry-section" id="entry" data-reveal data-scene><div><p className="ss-eyebrow">NICE TO MEET YOU, FUTURE TEAMMATE.</p><h2>まずは、<br/>話してみよう。</h2><p>あなたの好きなこと、これからのこと。<br/>選考の前に、お互いを知る時間から。</p><label className="next-entry-select">興味のある職種<select value={entry} onChange={e=>setEntry(e.target.value)}><option>まずはカジュアルに話したい</option>{jobs.map(j=><option key={j.title}>{j.title}</option>)}</select></label></div><DemoForm kind="応募" subject={entry}/></section></main><SiteFooter brand="next." tagline="THE NEXT IS YOURS. — その一歩が、チームの未来になる。"/>
{person!==null&&<Modal title={`${people[person].name} / ${people[person].role}`} close={()=>setPerson(null)}><img className="ss-modal-image next-portrait-detail" src={people[person].image} alt="インタビューの人物イメージ"/><h3 className="next-interview-title">{people[person].title}</h3><p>{people[person].body}</p><p className="ss-caption">デザインサンプル用の架空のインタビューです。</p><a className="ss-button" href="#jobs" onClick={()=>setPerson(null)}>一緒に働く仕事を見る</a></Modal>}
{job!==null&&<Modal title={jobs[job].title} close={()=>setJob(null)}><p className="ss-eyebrow">{jobs[job].category} / SAMPLE POSITION</p><h3>お任せしたいこと</h3><p>{jobs[job].body}</p><h3>こんな経験を歓迎します</h3><p>{jobs[job].skills}</p><dl className="ss-specs"><div><dt>働き方</dt><dd>チームでの協働を軸に、柔軟に相談</dd></div><div><dt>募集について</dt><dd>サイト体験用の架空の職種です。実際の採用は行いません。</dd></div></dl><a href="#entry" className="ss-button" onClick={()=>{setEntry(jobs[job].title);setJob(null);}}>この職種について話す</a></Modal>}
</div>;}
