import { AmbientVideo, HeroLines } from "./Motion";
import { useState } from "react";
import { asset, DemoBar, DemoForm, Modal, SiteFooter, SiteHeader } from "./Shared";
import "./sora.css";
import "../sample-fonts.css";
const works=[
 {title:"光を紡ぐ家",en:"HOUSE OF LIGHT",category:"住まい",image:"sora-courtyard.webp",area:"中庭のある住まい",body:"一日の光を、暮らしの風景に。外へと閉じ、庭へと開く住まいは、家族の気配と季節の移ろいをゆるやかにつなぎます。石、木、土。時間とともに表情を深める素材を選びました。"},
 {title:"庭と、ひと続きに。",en:"A ROOM WITH A GARDEN",category:"リノベーション",image:"sora-interior.webp",area:"庭を愉しむリノベーション",body:"窓辺に座り、風の通り道を感じる。残せるものを大切にしながら、庭と室内のあいだにある境界をほどきました。小さな変化から、住まいの新しい可能性が生まれます。"},
 {title:"森にほどける小屋",en:"RETREAT IN THE WOODS",category:"住まい",image:"sora-retreat.webp",area:"自然と過ごす小さな拠点",body:"木立の隙間に、そっと置くように。低く伸びる屋根と大きな開口が、森の景色を暮らしの一部にします。建物が主張するのではなく、そこにある自然を引き立てるための設計です。"}
];
export default function Sora(){
 const [filter,setFilter]=useState("すべて");const [work,setWork]=useState<number|null>(null);const [journal,setJournal]=useState<number|null>(null);
 return <div className="sample-full sora-page" id="top"><a className="ss-skip" href="#main">本文へ移動</a><DemoBar site="sora"/><SiteHeader logo={<>SORA<small>ARCHITECTS</small></>} links={[["私たちについて","#about"],["設計のかたち","#works"],["日々のこと","#journal"]]} action={<a href="#contact" className="ss-text-link">設計のご相談</a>}/>
 <main id="main"><section className="sora-hero" data-hero data-scene><img className="ss-photo-drift ss-loop" src={asset("sora-courtyard.webp")} alt="木々と石壁に囲まれた静かな中庭のある住まい" fetchPriority="high" width={1448} height={1086}/><AmbientVideo/><div className="sora-hero-copy"><p className="ss-eyebrow">SPACES FOR A SLOWER LIFE</p><h1><HeroLines first="余白と、" second="暮らす。"/></h1><p className="sora-english">Live with less. Feel a little more.</p></div><div className="sora-hero-foot"><a href="#about"><i className="sora-scroll-line" aria-hidden="true"/>SCROLL TO DISCOVER</a><button onClick={()=>setWork(0)}><span>光を紡ぐ家</span><span className="sora-project-read">設計を見る</span></button></div></section>
 <section className="ss-section sora-about" id="about" data-reveal><div><p data-scroll-anchor className="ss-eyebrow">01 / OUR PHILOSOPHY</p><h2>美しいのは、<br/>そこにある日常。</h2></div><div className="sora-prose"><p>朝の光が、壁をゆっくりと渡る。<br/>窓を開けると、庭の匂いがする。<br/>何でもない一日が、少し好きになる。</p><p>私たちが設計したいのは、<br/>そんな日々を受け止める、静かな場所です。</p><p>建築と自然、人と暮らし。<br/>そのあいだを、ていねいに。<br/>あなたらしい余白を、一緒に見つけていきます。</p><a className="ss-text-link" href="#process">家づくりの進め方</a></div></section>
 <section className="ss-section sora-works" id="works"><div className="ss-section-head" data-reveal><div><p data-scroll-anchor className="ss-eyebrow">02 / SELECTED WORKS</p><h2>暮らしの、かたち。</h2></div><div className="ss-filter" aria-label="作品の分類">{["すべて","住まい","リノベーション"].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="sora-project-grid">{works.map((w,i)=>(filter==="すべて"||w.category===filter)&&<button className="sora-project-card" key={w.title} onClick={()=>setWork(i)}><div className="sora-project-image"><img src={asset(w.image)} alt={w.title} width={1536} height={1024} loading="lazy"/></div><div className="sora-project-meta"><div><p className="ss-eyebrow">0{i+1} / {w.en}</p><h3>{w.title}</h3><small>{w.area}</small></div><span className="sora-project-action">設計を見る</span></div></button>)}</div><p className="ss-caption">オリジナルの建築コンセプトです。実在する設計実績ではありません。</p></section>
 <section className="sora-full-image" data-parallax="52" data-scene><img src={asset("sora-interior.webp")} alt="庭の緑とつながる、木と石のダイニング" loading="lazy" width={1536} height={1024}/><AmbientVideo/><p data-enter>季節を、迎え入れる。</p></section>
 <section className="ss-section sora-process" id="process" data-reveal><div><p data-scroll-anchor className="ss-eyebrow">03 / HOW WE DESIGN</p><h2>話すことから、<br/>始まる建築。</h2><p>暮らしの話を、たくさん聞かせてください。<br/>まだ輪郭のない想いも、大切な手がかりです。</p></div><ol>{[["対話する","好きな場所、普段の過ごし方、これからのこと。ご希望や敷地の状況を伺います。"],["かたちを探す","模型や図面を囲みながら、光・風・動線を検討。ご予算とともに計画を整えます。"],["ていねいにつくる","素材や細部を一つずつ選び、施工者と協力して、住まいをかたちにします。"],["暮らしを育てる","お引き渡しの先も、変わっていく暮らしと建築に寄り添っていきます。"]].map(([t,p],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></li>)}</ol></section>
 <section className="ss-section sora-journal" id="journal" data-reveal><div className="ss-section-head"><div><p data-scroll-anchor className="ss-eyebrow">04 / JOURNAL</p><h2>日々の、ひとこま。</h2></div><span className="ss-caption">設計のあいだに考えること。</span></div>{["素材と、長く付き合う。","窓は、風景を選ぶこと。"].map((t,i)=><button className="sora-journal-row" key={t} onClick={()=>setJournal(i)}><span>ESSAY / 0{i+1}</span><h3>{t}</h3><span className="sora-journal-action">記事を読む</span></button>)}</section>
 <section className="ss-section sora-contact" id="contact" data-reveal><div><p data-scroll-anchor className="ss-eyebrow">LET’S TALK ABOUT YOUR LIFE</p><h2>あなたの暮らしを、<br/>聞かせてください。</h2><p>新築も、リノベーションも。<br/>まずは、想いを言葉にするところから。</p></div><DemoForm kind="相談"/></section></main><SiteFooter brand="SORA" tagline="建築と自然、人と暮らし。そのあいだを、ていねいに。"/>
 {work!==null&&<Modal title={works[work].title} close={()=>setWork(null)}><img className="ss-modal-image" src={asset(works[work].image)} alt={works[work].area}/><p className="ss-eyebrow">CONCEPT PROJECT / {works[work].en}</p><p>{works[work].body}</p><dl className="ss-specs"><div><dt>テーマ</dt><dd>{works[work].area}</dd></div><div><dt>デザイン</dt><dd>光・自然素材・暮らしの余白</dd></div></dl><a href="#contact" className="ss-button" onClick={()=>setWork(null)}>こんな暮らしを相談する</a></Modal>}
 {journal!==null&&<Modal title={journal===0?"素材と、長く付き合う。":"窓は、風景を選ぶこと。"} close={()=>setJournal(null)}><p className="ss-eyebrow">SORA JOURNAL / DESIGN ESSAY</p><p>{journal===0?"手で触れたときの温度。光が当たったときの陰影。素材には、写真だけでは伝わらない豊かさがあります。私たちは仕上げの美しさだけでなく、使い続けることでどんな表情になるかを考えて選びます。":"窓の大きさを決める前に、その向こうに何が見えるかを考えます。隣の木の枝、遠くの空、足元の小さな草花。ひとつの窓が、毎日の暮らしに風景を連れてきます。"}</p><p>{journal===0?"木についた小さな傷も、石の色の変化も、暮らしの記憶になっていく。完成した日を出発点に、住む人とともに育つ建築を目指しています。":"光を取り込むだけでなく、外からの視線を整え、風の道をつくる。場所ごとに異なる答えを、現地に立ちながら探していきます。"}</p></Modal>}
 </div>;
}
